test_login (testCase.testcase_login.Login) ... ok
test_login_null (testCase.testcase_login_null.LoginNull) ... ok
test_login_error (testCase.testcase_login.Login) ... FAIL

======================================================================
FAIL: test_login_error (testCase.testcase_login.Login)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\monitor\PycharmProjects\ML\testCase\testcase_login.py", line 30, in test_login_error
    self.assertEqual(s['code'], -11)
AssertionError: -1 != -11

----------------------------------------------------------------------
Ran 3 tests in 0.071s

FAILED (failures=1)
test_login (testCase.testcase_login.Login) ... ERROR
test_login_null (testCase.testcase_login_null.LoginNull) ... ERROR
test_login_error (testCase.testcase_login.Login) ... ERROR
testGetnearbyplace (testCase.multilotto_get_config.TestML) ... ok

======================================================================
ERROR: test_login (testCase.testcase_login.Login)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\monitor\PycharmProjects\ML\testCase\testcase_login.py", line 21, in test_login
    s = json.loads(result)  # s为dict类型的返回结果
  File "D:\python3.6.5\lib\json\__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'

======================================================================
ERROR: test_login_null (testCase.testcase_login_null.LoginNull)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\monitor\PycharmProjects\ML\testCase\testcase_login_null.py", line 18, in test_login_null
    s = json.loads(result)  # s为dict类型的返回结果
  File "D:\python3.6.5\lib\json\__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'

======================================================================
ERROR: test_login_error (testCase.testcase_login.Login)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\monitor\PycharmProjects\ML\testCase\testcase_login.py", line 29, in test_login_error
    s = json.loads(result)
  File "D:\python3.6.5\lib\json\__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'

----------------------------------------------------------------------
Ran 4 tests in 2.995s

FAILED (errors=3)
test_login (testCase.testcase_login.Login) ... ok
test_login_null (testCase.testcase_login_null.LoginNull) ... ok
test_login_error (testCase.testcase_login.Login) ... ok
testGetnearbyplace (testCase.multilotto_get_config.TestML) ... ok

----------------------------------------------------------------------
Ran 4 tests in 2.197s

OK
test_login (testCase.testcase_login.Login) ... ok
test_login_null (testCase.testcase_login_null.LoginNull) ... ok
test_login_error (testCase.testcase_login.Login) ... ok
testGetnearbyplace (testCase.multilotto_get_config.TestML) ... ok

----------------------------------------------------------------------
Ran 4 tests in 1.790s

OK
